# Generated by Django 4.2.13 on 2024-11-30 12:04

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_statuscontrol_is_deleted_statuscontrol_open_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('when', models.CharField(blank=True, help_text='1d', max_length=10, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aplicación de consulta',
                'verbose_name_plural': 'Aplicaciones de consulta',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnews_url', models.URLField(max_length=800, unique=True)),
                ('real_url', models.URLField(blank=True, max_length=800, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('valid', models.BooleanField(blank=True, null=True)),
                ('querys', models.ManyToManyField(blank=True, related_name='links', to='news.applyquery')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=120, null=True)),
                ('pages', models.CharField(blank=True, max_length=80, null=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('structured_content', models.JSONField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('link_content_text', models.TextField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='news.link')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_news', models.BooleanField(default=True, verbose_name='Es una fuente de noticias')),
                ('main_url', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.SmallIntegerField(default=5)),
                ('exclude', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fuente de información',
                'verbose_name_plural': 'Fuentes de información',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_word', models.CharField(max_length=100, unique=True)),
                ('alternative_words', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='news.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='SourceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title_tag', models.CharField(max_length=200)),
                ('subtitle_tag', models.CharField(max_length=200)),
                ('content_tag', models.TextField()),
                ('validated', models.BooleanField(default=False)),
                ('sources', models.ManyToManyField(blank=True, related_name='methods', to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query', models.TextField(blank=True, null=True)),
                ('manual_query', models.TextField(blank=True, null=True)),
                ('use_manual_query', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('complementary_words', models.ManyToManyField(blank=True, related_name='complementary_queries', to='news.wordlist')),
                ('main_words', models.ManyToManyField(blank=True, related_name='main_queries', to='news.wordlist')),
                ('negative_words', models.ManyToManyField(blank=True, related_name='negative_queries', to='news.wordlist')),
                ('status_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=news.models.upload_to_note_file)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.note')),
            ],
            options={
                'verbose_name': 'Archivo de nota',
                'verbose_name_plural': 'Archivos de nota',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source', verbose_name='Fuente de información'),
        ),
        migrations.AddField(
            model_name='note',
            name='source_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='news.sourcemethod'),
        ),
        migrations.AddField(
            model_name='note',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol'),
        ),
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='news.source'),
        ),
        migrations.AddField(
            model_name='applyquery',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applys', to='news.searchquery'),
        ),
    ]
