# Generated by Django 4.2.13 on 2024-11-26 00:20

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnews_url', models.URLField(max_length=800)),
                ('real_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('valid', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_word', models.CharField(max_length=100, unique=True)),
                ('alternative_words', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=120, null=True)),
                ('pages', models.CharField(blank=True, max_length=80, null=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('structured_content', models.JSONField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='news.link')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query', models.TextField(blank=True, null=True)),
                ('when', models.CharField(blank=True, help_text='1d', max_length=10, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual_query', models.BooleanField(default=False)),
                ('automatic_query', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_news', models.BooleanField(default=True, verbose_name='Es una fuente de noticias')),
                ('main_url', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Fuente de información',
                'verbose_name_plural': 'Fuentes de información',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComplementaryGroup',
            fields=[
                ('listwords_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.listwords')),
            ],
            bases=('news.listwords',),
        ),
        migrations.CreateModel(
            name='MainGroup',
            fields=[
                ('listwords_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.listwords')),
            ],
            bases=('news.listwords',),
        ),
        migrations.CreateModel(
            name='NegativeGroup',
            fields=[
                ('listwords_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.listwords')),
            ],
            bases=('news.listwords',),
        ),
        migrations.CreateModel(
            name='SourceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title_tag', models.CharField(max_length=200)),
                ('subtitle_tag', models.CharField(max_length=200)),
                ('content_tag', models.TextField()),
                ('validated', models.BooleanField(default=False)),
                ('sources', models.ManyToManyField(blank=True, related_name='methods', to='news.source')),
            ],
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=news.models.upload_to_note_file)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.note')),
            ],
            options={
                'verbose_name': 'Archivo de nota',
                'verbose_name_plural': 'Archivos de nota',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source', verbose_name='Fuente de información'),
        ),
        migrations.AddField(
            model_name='note',
            name='source_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='news.sourcemethod'),
        ),
        migrations.AddField(
            model_name='note',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol'),
        ),
        migrations.AddField(
            model_name='link',
            name='querys',
            field=models.ManyToManyField(blank=True, related_name='links', to='news.searchquery'),
        ),
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='news.source'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='complementary_words',
            field=models.ManyToManyField(blank=True, related_name='queries', to='news.complementarygroup'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='main_words',
            field=models.ManyToManyField(blank=True, related_name='queries', to='news.maingroup'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='negative_words',
            field=models.ManyToManyField(blank=True, related_name='queries', to='news.negativegroup'),
        ),
    ]
