# Generated by Django 4.2.13 on 2024-11-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_statuscontrol_is_deleted_statuscontrol_open_editor_and_more'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='use_automatic_query',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='use_manual_query',
            field=models.BooleanField(default=True),
        ),
    ]
