# Generated by Django 4.2.13 on 2024-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='when',
            field=models.CharField(default='1d', max_length=10),
        ),
    ]
