# Generated by Django 4.2.13 on 2024-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='gnews_url',
            field=models.URLField(max_length=800, unique=True),
        ),
    ]
