# Generated by Django 4.2.13 on 2024-11-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordlist',
            options={'ordering': ['cluster', 'main_word'], 'verbose_name': 'Lista de palabras', 'verbose_name_plural': 'Listas de palabras'},
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='news.cluster'),
            preserve_default=False,
        ),
    ]
