# Generated by Django 4.2.13 on 2024-11-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_searchquery_use_automatic_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
