# Generated by Django 4.2.13 on 2024-07-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_link_source_searchquery_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.TextField(),
        ),
    ]
