# Generated by Django 4.2.13 on 2024-11-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_wordlist_options_alter_wordlist_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='querys',
            new_name='queries',
        ),
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
    ]
