# Generated by Django 4.2.13 on 2024-11-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_link_gnews_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('public_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='listwords',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listwords',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='news.cluster'),
        ),
    ]
