# Generated by Django 4.2.13 on 2024-07-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_searchquery_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.sourcemethod'),
        ),
    ]
