# Generated by Django 4.2.13 on 2024-11-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_source_exclude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterField(
            model_name='link',
            name='real_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
