# Generated by Django 4.2.13 on 2024-07-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_source_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='gnews_url',
            field=models.URLField(max_length=800),
        ),
    ]
