# Generated by Django 4.2.13 on 2024-12-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_valid_link_is_dfi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='source',
            name='is_foreign',
            field=models.BooleanField(default=False, verbose_name='Es extranjera no internacional'),
        ),
        migrations.AddField(
            model_name='source',
            name='is_scrapable',
            field=models.BooleanField(default=True, verbose_name='Es escrapeable'),
        ),
    ]
