# Generated by Django 4.2.13 on 2024-12-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_source_is_active_source_is_foreign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='is_scrapable',
        ),
        migrations.AddField(
            model_name='source',
            name='has_content',
            field=models.BooleanField(blank=True, null=True, verbose_name='Es scrapeable'),
        ),
        migrations.AddField(
            model_name='source',
            name='scraper_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Activa'),
        ),
    ]
