# Generated by Django 4.2.13 on 2024-12-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_source_nacional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='nacional',
            new_name='national',
        ),
    ]
