# Generated by Django 4.2.13 on 2024-12-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_rename_nacional_source_national'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='exclude',
        ),
        migrations.RemoveField(
            model_name='source',
            name='is_foreign',
        ),
    ]
