# Generated by Django 4.2.13 on 2024-12-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_source_exclude_remove_source_is_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='pre_is_dfi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
