# Generated by Django 4.2.13 on 2024-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_link_pre_is_dfi'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='gnews_entry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
