# Generated by Django 4.2.13 on 2024-12-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_link_gnews_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='soft_negative_words',
            field=models.ManyToManyField(blank=True, related_name='soft_negative_queries', to='news.wordlist'),
        ),
    ]
