# Generated by Django 4.2.13 on 2024-12-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_searchquery_soft_negative_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='soft_negative_words',
        ),
    ]
