# Generated by Django 4.2.13 on 2024-12-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_searchquery_soft_negative_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyquery',
            name='when',
        ),
        migrations.AlterField(
            model_name='applyquery',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_queries', to='news.searchquery'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
