# Generated by Django 4.2.13 on 2024-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_applyquery_when_alter_applyquery_search_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='pre_national',
            field=models.CharField(blank=True, choices=[('Nal', 'Nacional'), ('Int', 'Internacional'), ('For', 'Extranjera')], max_length=3, null=True),
        ),
    ]
