# Generated by Django 4.2.13 on 2024-12-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_applyquery_when_alter_applyquery_search_query_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='NoteLink',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='link',
            new_name='note_link',
        ),
    ]
