# Generated by Django 4.2.13 on 2024-12-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_statuscontrol_is_deleted_statuscontrol_open_editor_and_more'),
        ('news', '0016_rename_link_notelink_rename_link_note_note_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelink',
            name='queries',
            field=models.ManyToManyField(blank=True, related_name='note_links', to='news.applyquery'),
        ),
        migrations.AlterField(
            model_name='notelink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='news.source'),
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='NoteContent',
        ),
        migrations.AlterField(
            model_name='notefile',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='news.notecontent'),
        ),
    ]
