# Generated by Django 4.2.13 on 2024-12-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_notelink_queries_alter_notelink_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecontent',
            name='note_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_contents', to='news.notelink'),
        ),
        migrations.AlterField(
            model_name='notecontent',
            name='source_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_contents', to='news.sourcemethod'),
        ),
    ]
