# Generated by Django 4.2.13 on 2024-12-04 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_source_pre_national'),
        ('news', '0018_alter_notecontent_note_link_and_more'),
    ]

    operations = [
    ]
