# Generated by Django 4.2.13 on 2024-12-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_merge_20241204_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordlist',
            options={'ordering': ['cluster', 'name'], 'verbose_name': 'Lista de palabras', 'verbose_name_plural': 'Listas de palabras'},
        ),
        migrations.RenameField(
            model_name='wordlist',
            old_name='main_word',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RenameField(
            model_name='wordlist',
            old_name='alternative_words',
            new_name='query_words',
        ),
        migrations.RenameField(
            model_name='wordlist',
            old_name='description',
            new_name='soft_query_words',
        ),
    ]
