# Generated by Django 4.2.13 on 2024-12-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_wordlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyquery',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applyquery',
            name='has_errors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applyquery',
            name='last_feed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
