# Generated by Django 4.2.13 on 2024-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_applyquery_errors_applyquery_has_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelink',
            name='gnews_url',
            field=models.URLField(max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='use_manual_query',
            field=models.BooleanField(default=False),
        ),
    ]
