# Generated by Django 4.2.13 on 2024-12-06 14:25

from django.db import migrations, models


def add_is_internal_dis(apps, schema_editor):
    NoteLink = apps.get_model('news', 'NoteLink')
    is_dfi = NoteLink.objects.filter(is_dfi=True)
    is_dfi.update(is_internal_dis='valid')
    is_not_dfi = NoteLink.objects.filter(is_dfi=False)
    is_not_dfi.update(is_internal_dis='invalid')


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_notelink_gnews_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notelink',
            name='is_internal_dis',
            field=models.CharField(blank=True, choices=[('valid', 'Válido'), ('invalid', 'Inválido'), ('unknown', 'Desconocido')], max_length=10, null=True),
        ),
        migrations.RunPython(add_is_internal_dis),
    ]
