# Generated by Django 4.2.13 on 2024-12-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_notelink_is_internal_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecontent',
            name='structured_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
