# Generated by Django 4.2.13 on 2024-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_alter_notecontent_structured_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notelink',
            name='title',
            field=models.TextField(),
        ),
    ]
