# Generated by Django 4.2.13 on 2024-12-06 19:31

from django.db import migrations, models
import django.db.models.deletion


def create_source_origins(apps, schema_editor):
    NATIONAL_CHOICES = [
        (None, 'Desconocido', 'blue-grey', False),
        ('Nal', 'Nacional', 'success', True),
        ('Int', 'Internacional', 'primary', True),
        ('For', 'Extranjera', 'pink', False),
    ]
    SourceOrigin = apps.get_model('news', 'SourceOrigin')
    for order, (old_name, name, color, in_scope) in enumerate(NATIONAL_CHOICES):
        SourceOrigin.objects.get_or_create(
            name=name,
            old_name=old_name,
            defaults=dict(
                color=color,
                order=order,
                # in_scope=in_scope
            )
        )
    Source = apps.get_model('news', 'Source')
    for source_origin in SourceOrigin.objects.all():
        Source.objects\
            .filter(national=source_origin.old_name)\
            .update(source_origin=source_origin)
        Source.objects\
            .filter(pre_national=source_origin.old_name)\
            .update(pre_source_origin=source_origin)
    empty_source_origin = SourceOrigin.objects.get(name='Desconocido')
    Source.objects\
        .filter(national__isnull=True)\
        .update(source_origin=empty_source_origin)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_alter_notelink_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('old_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Origen de fuente (National)',
                'verbose_name_plural': 'Orígenes de fuente (National)',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='pre_source_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_sources', to='news.sourceorigin'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.sourceorigin'),
        ),
        migrations.RunPython(create_source_origins),
        # default value for source_origin to 1
        migrations.AlterField(
            model_name='source',
            name='source_origin',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='news.sourceorigin'),
        ),
    ]
