# Generated by Django 4.2.13 on 2024-12-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_sourceorigin_source_pre_source_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceorigin',
            name='in_scope',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.sourceorigin'),
        ),
    ]
