# Generated by Django 4.2.13 on 2024-12-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_sourceorigin_in_scope_alter_source_source_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name'], 'verbose_name': 'Fuente de información', 'verbose_name_plural': 'Fuentes de información'},
        ),
        migrations.RemoveField(
            model_name='source',
            name='is_news',
        ),
        migrations.RemoveField(
            model_name='source',
            name='order',
        ),
    ]
