# Generated by Django 4.2.13 on 2024-12-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_remove_source_national'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Opción de validación',
                'verbose_name_plural': 'Opciones de validación',
                'ordering': ['order'],
            },
        ),
    ]
