# Generated by Django 4.2.13 on 2024-11-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontrol',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statuscontrol',
            name='open_editor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statuscontrol',
            name='group',
            field=models.CharField(choices=[('register', 'Registro'), ('validation', 'Validación'), ('location', 'Ubicación')], default='petition', max_length=10, verbose_name='grupo de status'),
        ),
    ]
