# Generated by Django 4.2.13 on 2024-12-07 11:41

from django.db import migrations, models
import note.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=120, null=True)),
                ('pages', models.CharField(blank=True, max_length=80, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_full', models.TextField(blank=True, null=True)),
                ('full_html', models.TextField(blank=True, null=True)),
                ('full_text', models.TextField(blank=True, null=True)),
                ('structured_content', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=note.models.upload_to_note_file)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo de nota',
                'verbose_name_plural': 'Archivos de nota',
            },
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnews_url', models.URLField(max_length=1500, unique=True)),
                ('real_url', models.URLField(blank=True, max_length=800, null=True)),
                ('title', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('gnews_entry', models.JSONField(blank=True, null=True)),
                ('is_dfi', models.BooleanField(blank=True, null=True)),
                ('is_internal_dis', models.CharField(blank=True, choices=[('valid', 'Válido'), ('invalid', 'Inválido'), ('unknown', 'Desconocido')], max_length=10, null=True)),
                ('pre_is_dfi', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
