# Generated by Django 4.2.13 on 2024-12-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0001_initial'),
        ('category', '0002_statuscontrol_is_deleted_statuscontrol_open_editor_and_more'),
        ('source', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notelink',
            name='queries',
            field=models.ManyToManyField(blank=True, related_name='note_links', to='search.applyquery'),
        ),
        migrations.AddField(
            model_name='notelink',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='source.source'),
        ),
        migrations.AddField(
            model_name='notefile',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='note.notecontent'),
        ),
        migrations.AddField(
            model_name='notecontent',
            name='note_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_contents', to='note.notelink'),
        ),
        migrations.AddField(
            model_name='notecontent',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source', verbose_name='Fuente de información'),
        ),
        migrations.AddField(
            model_name='notecontent',
            name='source_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_contents', to='source.sourcemethod'),
        ),
        migrations.AddField(
            model_name='notecontent',
            name='status_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol'),
        ),
    ]
