# Generated by Django 4.2.13 on 2024-12-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_validoption_notelink_valid_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='notelink',
            name='pre_valid_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_valid_option', to='note.validoption'),
        ),
        migrations.AlterField(
            model_name='notelink',
            name='valid_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valid_option', to='note.validoption'),
        ),
    ]
