# Generated by Django 4.2.13 on 2024-12-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_notelink_pre_valid_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notelink',
            name='pre_is_dfi',
        ),
    ]
