# Generated by Django 4.2.13 on 2024-12-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_statuscontrol_is_deleted_statuscontrol_open_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('query_words', models.TextField(blank=True, null=True)),
                ('soft_query_words', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='search.cluster')),
            ],
            options={
                'verbose_name': 'Lista de palabras',
                'verbose_name_plural': 'Listas de palabras',
                'ordering': ['cluster', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query', models.TextField(blank=True, null=True)),
                ('manual_query', models.TextField(blank=True, null=True)),
                ('use_manual_query', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('complementary_words', models.ManyToManyField(blank=True, related_name='complementary_queries', to='search.wordlist')),
                ('main_words', models.ManyToManyField(blank=True, related_name='main_queries', to='search.wordlist')),
                ('negative_words', models.ManyToManyField(blank=True, related_name='negative_queries', to='search.wordlist')),
                ('status_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.statuscontrol')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='ApplyQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('has_errors', models.BooleanField(default=False)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('last_feed', models.JSONField(blank=True, null=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_queries', to='search.searchquery')),
            ],
            options={
                'verbose_name': 'Aplicación de consulta',
                'verbose_name_plural': 'Aplicaciones de consulta',
            },
        ),
    ]
