# Generated by Django 4.2.13 on 2024-12-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_url', models.CharField(blank=True, max_length=100, null=True)),
                ('has_content', models.BooleanField(blank=True, null=True, verbose_name='Es scrapeable')),
                ('scraper_message', models.TextField(blank=True, null=True)),
                ('national', models.CharField(blank=True, choices=[('Nal', 'Nacional'), ('Int', 'Internacional'), ('For', 'Extranjera')], max_length=3, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='Activa')),
                ('pre_national', models.CharField(blank=True, choices=[('Nal', 'Nacional'), ('Int', 'Internacional'), ('For', 'Extranjera')], max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Fuente de información',
                'verbose_name_plural': 'Fuentes de información',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('old_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.SmallIntegerField(default=5)),
                ('in_scope', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Origen de fuente (National)',
                'verbose_name_plural': 'Orígenes de fuente (National)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SourceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle_tag', models.CharField(blank=True, max_length=200, null=True)),
                ('content_tag', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='source.source')),
            ],
            options={
                'verbose_name': 'Método de fuente',
                'verbose_name_plural': 'Métodos de fuente',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='pre_source_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_sources', to='source.sourceorigin'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='source.sourceorigin'),
        ),
    ]
