# Generated by Django 4.2.13 on 2024-12-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_create_source_origins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='national',
        ),
    ]
