# Generated by Django 4.2.13 on 2024-12-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_remove_source_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='origin_checked',
            field=models.BooleanField(default=False, verbose_name='Origen verificado'),
        ),
    ]
