# Generated by Django 4.2.13 on 2024-12-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_source_origin_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='pre_national',
        ),
    ]
