# Generated by Django 4.2.13 on 2025-08-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_remove_source_pre_national'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceorigin',
            name='in_scope',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
